<?php

namespace app\models;

//use Yii;
//use yii\imagine\Image;
//use app\components;
use yii\base\Exception;

/**
 * This is the model class for table "post".
 *
 */
class Post extends \yii\db\ActiveRecord
{
    public $fileImage;
    public $miniature_img;
    public $socNet_check;
//    public $miniature_url;
    public $questions;
    public $questionnaire;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'post';
    }


    public function beforeSave($insert)
    {
        if (parent::beforeSave($insert)) {
            $myclass = new \app\components\MyClass();
            if ($this->waterMark_check == 1) {
                if ($this->description != '') {
                    $this->description = $myclass->imgUploadUpdate($this->description, true);
                }
                if ($this->miniature_url != '') {
                    $this->miniature_url = $myclass->imgUploadUpdate($this->miniature_url, true);
                }
            } else {
                $this->description = $myclass->imgUploadUpdate($this->description, false);
                $this->miniature_url = $myclass->imgUploadUpdate($this->miniature_url, false);
            }

            return true;
        }
        return false;
    }


//    public function afterSave($insert, $changedAttributes)
//    {
//        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
//        $myclass = new components\MyClass();
//        if ($this->miniature_url != '') {
//            $myclass->imgUploadUpdate($this->model);
//        }
//    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['type_id', 'user_id', 'category_id', 'at_date', 'status_id', 'poll_id', 'commentsOn_check', 'regionNews_check', 'importantNews_check', 'pressRelease_check', 'adult_check', 'hotNew_check', 'authorText_check', 'waterMark_check', 'specTopic_id'], 'integer'],
            [['slogan', 'description', 'questions', 'questionnaire'], 'string'],
            [['title', 'author', 'source_url'], 'string', 'max' => 255],
            [['source_name', 'video_url', 'miniature_url', 'miniature_desc', 'metaKeyword'], 'string', 'max' => 500],
            [['type_id'], 'exist', 'skipOnError' => true, 'targetClass' => Type::className(), 'targetAttribute' => ['type_id' => 'id']],
            [['poll_id'], 'exist', 'skipOnError' => true, 'targetClass' => Poll::className(), 'targetAttribute' => ['poll_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
//            [['poll_id'], 'exist', 'skipOnError' => true, 'targetClass' => Poll!!!::className(), 'targetAttribute' => ['poll_id' => 'id']],
            [['specTopic_id'], 'exist', 'skipOnError' => true, 'targetClass' => Spectopic::className(), 'targetAttribute' => ['specTopic_id' => 'id']],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => Cat::className(), 'targetAttribute' => ['category_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'at_date' => 'Время публикации',
            'type_id' => 'Тип новости',
            'user_id' => 'User ID',
            'category_id' => 'Рубрика',
            'title' => 'Заголовок',
            'slogan' => 'Фишка (Слоган)',
            'description' => 'Текст',
            'author' => 'Автор публикации',
            'source_url' => 'Источник (http://)',
            'source_name' => 'Название источника',
            'poll_id' => 'Голос города',
            'video_url' => 'Video Url',
            'status_id' => 'Status ID',
            'commentsOn_check' => 'Разрешить комментировать статью',
            'waterMark_check' => 'Водяной знак',
            'authorText_check' => 'Авторский или переработанный текст',
            'regionNews_check' => 'Региональная новость',
            'socNet_check' => 'Опубликовать в социальных сетях',
            'importantNews_check' => 'Добавить в блок "Важные новости"',
            'pressRelease_check' => 'Новость подготовлена по пресс-релизу',
            'adult_check' => 'Контент 18+',
            'hotNew_check' => 'Новость дня',
            'miniature_url' => 'Фото',
            'miniature_desc' => 'Подпись фото',
            'specTopic_id' => 'Спецтопик',
            'metaKeyword' => 'Ключевые слова',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMetakeywords()
    {
        return $this->hasMany(Metakeywords::className(), ['post_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getType()
    {
        return $this->hasOne(Type::className(), ['id' => 'type_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }


    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSpecTopic()
    {
        return $this->hasOne(Spectopic::className(), ['id' => 'specTopic_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Cat::className(), ['id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStatus()
    {
        return $this->hasOne(Status::className(), ['id' => 'status_id']);
    }







}
